# main.py — Generated by VIA for: "Create a todo list app with a React frontend, a FastAPI backend with endpoints to add, delete, and fetch todos, and API documentation."
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

import os

app = FastAPI(
    title="Create A Todo List App With",
    description="Generated by VIA — Autonomous AI Digital Team",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

items_data = [{"id": 1, "title": "Sample", "status": "active", "description": "Auto-generated"}]

@app.get("/")
def root():
    return {"app": "Create A Todo List App With", "status": "running", "docs": "/docs", "api": "/api/v1/items"}

@app.get("/health")
def health():
    return {"status": "healthy"}


@app.get("/api/v1/items")
def get_items():
    return {"items": items_data, "total": len(items_data)}

@app.get("/api/v1/items/{item_id}")
def get_item(item_id: int):
    item = next((i for i in items_data if i["id"] == item_id), None)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return item

@app.post("/api/v1/items")
def create_item(item: dict):
    item["id"] = len(items_data) + 1
    items_data.append(item)
    return item

@app.put("/api/v1/items/{item_id}")
def update_item(item_id: int, update: dict):
    for i, item in enumerate(items_data):
        if item["id"] == item_id:
            items_data[i].update(update)
            return items_data[i]
    raise HTTPException(status_code=404, detail="Item not found")

@app.delete("/api/v1/items/{item_id}")
def delete_item(item_id: int):
    global items_data
    items_data = [i for i in items_data if i["id"] != item_id]
    return {"deleted": item_id}

@app.get("/api/v1/stats")
def get_stats():
    return {"total": len(items_data), "active": sum(1 for i in items_data if i.get("status") == "active")}

# ── Route aliases: /api/v1/tasks and /tasks mirror /api/v1/items ────
@app.get("/api/v1/tasks")
def alias_get_tasks():
    return get_items()

@app.post("/api/v1/tasks")
def alias_create_tasks(item: dict):
    return create_item(item=item)

@app.get("/api/v1/tasks/{item_id}")
def alias_get_tasks_one(item_id: int):
    return get_item(item_id=item_id)

@app.put("/api/v1/tasks/{item_id}")
def alias_update_tasks(item_id: int, update: dict):
    return update_item(item_id=item_id, update=update)

@app.delete("/api/v1/tasks/{item_id}")
def alias_delete_tasks(item_id: int):
    return delete_item(item_id=item_id)

@app.get("/tasks")
def alias_get_tasks_short():
    return get_items()

@app.post("/tasks")
def alias_create_tasks_short(item: dict):
    return create_item(item=item)

@app.get("/tasks/{item_id}")
def alias_get_tasks_short_one(item_id: int):
    return get_item(item_id=item_id)

@app.put("/tasks/{item_id}")
def alias_update_tasks_short(item_id: int, update: dict):
    return update_item(item_id=item_id, update=update)

@app.delete("/tasks/{item_id}")
def alias_delete_tasks_short(item_id: int):
    return delete_item(item_id=item_id)


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False)
